# Generated by Django 2.2.2 on 2019-06-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('Latitude', models.CharField(max_length=500)),
                ('Longitude', models.CharField(max_length=500)),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMusica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('TipoMusica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoMusica')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(height_field=500, upload_to='images/', width_field=800)),
                ('TipoMusica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoMusica')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Local')),
            ],
        ),
    ]
