# Generated by Django 2.2.2 on 2019-07-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Imagem', models.ImageField(upload_to='images/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoNarrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('VideoUrl', models.CharField(max_length=500)),
                ('Modelo', models.CharField(choices=[('MUSI', 'Músicos'), ('FREQ', 'Frequentadores - Fãs - Consumidores'), ('OUTR', 'Outras Vozes')], max_length=5)),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('VideoUrl', models.CharField(max_length=500)),
                ('Modelo', models.CharField(choices=[('MUGR', 'Músicas/Grupos'), ('NARR', 'Narrativas'), ('CORP', 'Corpos')], max_length=10)),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstruturaSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Descricao', models.TextField()),
                ('Imagem', models.ImageField(upload_to='images/')),
                ('BlocoSite', models.CharField(choices=[('Espacos', 'Espaços'), ('Musicas', 'Músicas'), ('Grupos', 'Grupos'), ('Corpos', 'Corpos'), ('Narrativas', 'Narrativas')], max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
